# Generated by Django 6.0.5 on 2026-05-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_url', models.CharField(max_length=500, verbose_name='Caminho da Imagem (Ex: img/capa.png)')),
                ('link_compra', models.URLField(verbose_name='Link de Compra (Amazon)')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria (Ex: fantasia, distopia)')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.livro', verbose_name='Livro')),
            ],
            options={
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
